{
	"patcher" : 	{
		"fileversion" : 1,
		"appversion" : 		{
			"major" : 8,
			"minor" : 0,
			"revision" : 3,
			"architecture" : "x64",
			"modernui" : 1
		}
,
		"classnamespace" : "box",
		"rect" : [ 1447.0, 79.0, 1959.0, 1327.0 ],
		"bglocked" : 0,
		"openinpresentation" : 0,
		"default_fontsize" : 12.0,
		"default_fontface" : 0,
		"default_fontname" : "Arial",
		"gridonopen" : 1,
		"gridsize" : [ 15.0, 15.0 ],
		"gridsnaponopen" : 1,
		"objectsnaponopen" : 1,
		"statusbarvisible" : 2,
		"toolbarvisible" : 1,
		"lefttoolbarpinned" : 0,
		"toptoolbarpinned" : 0,
		"righttoolbarpinned" : 0,
		"bottomtoolbarpinned" : 0,
		"toolbars_unpinned_last_save" : 0,
		"tallnewobj" : 0,
		"boxanimatetime" : 200,
		"enablehscroll" : 1,
		"enablevscroll" : 1,
		"devicewidth" : 0.0,
		"description" : "",
		"digest" : "",
		"tags" : "",
		"style" : "",
		"subpatcher_template" : "",
		"boxes" : [ 			{
				"box" : 				{
					"bgcolor" : [ 0.094118, 0.113725, 0.137255, 1.0 ],
					"fgcolor" : [ 0.0, 1.0, 0.0, 1.0 ],
					"gridcolor" : [ 0.301961, 0.337255, 0.403922, 0.25098 ],
					"id" : "obj-13",
					"maxclass" : "scope~",
					"numinlets" : 2,
					"numoutlets" : 0,
					"patching_rect" : [ 817.0, 641.0, 100.0, 50.0 ],
					"prototypename" : "M4L.yellow"
				}

			}
, 			{
				"box" : 				{
					"bgcolor" : [ 0.094118, 0.113725, 0.137255, 1.0 ],
					"fgcolor" : [ 0.0, 1.0, 0.0, 1.0 ],
					"gridcolor" : [ 0.301961, 0.337255, 0.403922, 0.25098 ],
					"id" : "obj-11",
					"maxclass" : "scope~",
					"numinlets" : 2,
					"numoutlets" : 0,
					"patching_rect" : [ 885.0, 500.0, 100.0, 50.0 ],
					"prototypename" : "M4L.yellow"
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-10",
					"maxclass" : "newobj",
					"numinlets" : 3,
					"numoutlets" : 2,
					"outlettype" : [ "signal", "bang" ],
					"patching_rect" : [ 781.0, 429.0, 89.0, 22.0 ],
					"text" : "train~ 2000 0.1"
				}

			}
, 			{
				"box" : 				{
					"bitcode" : "QkPA3jUUAAAFAAAAYgwwJElZvubt834tRAEyBQAAAAAhDAAAXgcAAAuCIAACAAAAEwAAAAeBI5FByARJBhAyOZIBhAwlBQgZHgSLYoAcRQJCkgtC5BAyFDgIGEsKMnKISJAUIENGiKUAGTJC5EgOkJEjxFBBUYGM4YPligQ5RgZRGAAAHQAAABuIIACWDYTw/////wMgbUCG/////x8AOAAkgNpAEACQbDAKAViAaoNhBMACVBuQ4/////8HAA4ACag2GEgALAC1wUj+////fwAkgNpgKP////8/AHAASBuQZQASYAGoDQhDAAmwANUGo/n/////AWgDQAIASRgAAAsAAAAThECYIATDBIEQJgTFBME4JgjIMCFIJgTDBCFQJgTGBCJYGGGCEDQTAgEAAIkgAABTAAAAMiLICSBkhQSTI6SEBJMj44ShkBQSTI6MC4TkTBCswxwBkhIACiQLgAZZAaBCUgDokBYASmQXgBY5AaBGIgDokRAAimQKgCZZAKBKGgDokhEAyqQDgDbZAKBOEgDokw8ACuUCgEaZAaBSagDolBcASo0AEKAIKxa15gjAIAVeQwAJCBJLgdg90hRRwuQP0sNgg/Qg5vWCyWazWSwWi8WIVoRVjWxzBKBQBBaOciWo0a4MKxaLehQrxIrF+hGwICsW6xeLxWIkLMaKxfrFYkQsxYr1Y7HIeI00RZQw+a4ILhSBGpbP53MFg8PhsFg8ErIMq1qSlEV41YhZhlftRc4ixGIELcLqRdIyrGovohZixWKxyHqPNEWUMPkmMQHgQhFIYF0JW4RVlrT0K8Wq9uJyqTtHEBRjxQLgXl8CDwQQi3w0JBe96DoFQDgAAAAbyqAc2qAd9OAd2iAd7IAO9MAO6KANzAEP4EAP4kAO8KAN3AEP9CAO7EAP5kAO9MAO6KANZiEO5AAPdB6IIUNGiogADAZSGHAYTmHAYkCFAY+BFQZMhlgYcBlmYcBmoIUBn+EWBowGXBiwGFJhwGJQhQGnQRcGbIZaGLAadmHAaMiFAa8BHAZsBlsY8BhaYcBsCIcBj8EVBtwGchiwG8xhwGwQhwG/4RwGzIZxGPAYXmHAYliFAYOhFAYMB3QYcBvKYcBgMIUBq4EXBhyHdBgwGWRhwHJQhwHPgR0GTId2GPAYYGHAcliHAdPBHQashl4YsBp8YcBq+IXBkKcNgAAIBAAAAAAAAGDIYwcAAAgCAAAAAAAAMOSxAwAAAgAAAAAAAAAY8uQBEAADAAAAAAAAAAx57AAAAEEAAAAAAAAAhjx7AADAAAAAAAAAAABDHlUAAIAQAAAAAAAAgCEPKwAAUAAAAAAAAADAkIcVAAAwAAAAAAAAAGDIwwoAABgAAAAAAAAAMORxBQAADAAAAAAAAAAY8rgCAAAGAAAAAAAAAAx5YAEIgAMAAAAAAAAAhjywAATAAQAAAAAAAABDHlgAAAABAAAAAAAAgCGPLAAAgAAAAAAAAADAkMcOAABIAAAAAAAAAGDIYwcAACQAAAAAAAAAMOShBQAAEgAAAAAAAAAY8ugCAAAKAAAAAAAAAAx5egEAgAUAAAAAAAAAhjy0AABAAgAAAAAAAABDHloAACABAAAAAAAAgCEPOAABwAAAAAAAAACAxAcyBSQ2CBQmMgAAyAIBAADFAAAAMh6YHBkRTJCMCSZHxgRDCmhkTrPpZbmLnRa/wnU6+i3XqF2fp8cudlr8YqfHZfe8rFG7Pk+PXey0+GUvy+fpt5sGugbKOjtdn4OeLtC0naajQSj1ew4K00Hjsbwdds3pYbf5LSe7yuR6igpKmdNselnuYqfFr/Ebnpenz2i6UsZwfU4HGdNselkOYqbF8rA8r5Q5zaaX5S52WvySl81ledk9LivVrs/TYxc7LX6Ry3B5eRyml8l00ElZZ6frc9DTBZq203Q0KJlM6tQO09Eudlr8Ipfh8vI4TC+TdWIeoUzQPU1Hg8r4cRlOT7/dOrXr8/TYxU6LX+M3PC9Pn9F0nd7zcZrNDtPfchc7LX65w+0yJbQyp9n0stzFTotf5DJcXh6H6WWyVu/5OM1mh+lvuYudFr/CdTr6LaeF8gIVnZ6D2GmxPCzPg9JzELkMl5fHYXqZDAq7yaD0HOR+00HtcNpND6fdZTIo7M633/KyC5Skg+5pNhskLoPk5fbbXiaD0m5QsH6uz+kgGSx2c1FDJXOaTS/LXey0+MVOj8vueVklc5pNL8td7LT4ZS/L5+m3W6V2mI52sdPi1/gNz8vTZzSdHnpMqcsWzTWjiD7mNJtelrvYafHLHW6X9WmH6WgXOy1+het09FtOE0UDNJ0On+ter/FY3g675vSw2/yWk11lcv3lV7/nL3OaTS/L5y+qLFH7dr9EAzDEErVf10vQF00vUUQERJctwFUzPcoo1A7T0S52Wvxip8dl97ysUDtMR7vYafHLXpbP02+3Qu36PD12sdPiV7hOR7/ltNGmHaajXey0+OUOt8vaNOvz9BjETIvlYXmeOso0w3Q0iJkWy8PyPH12qH2aQuq06/P02MVOi1/ucLtMI1XM4fqcfi67WzUqKfaej9Nsdpj+lrvYafFr/Ibn5ekzmq6YMVyf00HP+TjNZofpbzmImRbLw/I8nTR7z8dpNjtMf8td7LT4RS7D5eVxmF4mU0qt93ycZrPD9LfcxU6LX+z0uOyel9V6z8dpNjtMf8td7LT4ZS/L5+m3GwCxGAAAVgAAADMIgBzE4RxmFAE9iEM4hMOMQoAHeXgHc5hxDOYAD+0QDvSADjMMQh7CwR3OoRxmMAU9iEM4hIMbzAM9yEM9jAM9zHiMdHAHewgHeUiHcHAHenADdniHcCCHGcwRDuyQDuEwD24wD+PwDvBQDjMQxB3eIRzYIR3CYR5mMIk7vIM70EM5tAM8vIM8hAM7zPAUdmAHe2gHN2iHcmgHN4CHcJCHcGAHdigHdvgFdniHd4CHXwiHcRiHcpiHeZiBLO7wDu7gDvXADuwwA2LIoRzkoRzMoRzkoRzcYRzKIRzEgR3KYQbWkEM5yEM5mEM5yEM5uMM4lEM4iAM7lMMvvIM8/II71AM7sMMMx2mHcFiHcnCDdGgHeGCHdBiHdKCHGc5TD+4AD/JQDuSQDuNAD+EgDuxQDjMgKB3cwR7CQR7SIRzcgR7c4Bzk4R3qAR5mGFE4sEM6nIM7AAAAqRgAAAYAAAALCnIoh3eAB3pYcJhDPbjDOLBDOdADAABhIAAACAAAABMEAYYDAQAABAAAAOY2DNJzAAvRTBH2B4sjKAAAAAAAYSAAAAoAAAATBMEFrB0xKIAQBIM2KIUAw4EAAAMAAAAHUBDNFGHmNgzSAwAAAAAAYSAAAAgAAAATBAGGAwEAAAQAAADmNgzScwAL0UwR9geLIygAAAAAAGEgAAAOAAAAEwRBLBAAAAACAAAAhCvARhAAAAAjBgUQgmCQB6EQXFDbDMKBAAAAAAIAAAAHUBDNFGEAAAAAAABhIAAAMQAAABMEQSwQAAAAFgAAAIQbAaBXIZRBQRQFsYY6KksN8AAe8AAeKDZGAIIgCIIgCKI2SIwRgCAIgiAIgmAKEmMEIAiCIAiCoP6GxBjBPpa8Ppa8Pob/QKyhjspKAzyABzyABwAAAADHjJcCFtnIwWkWCnxkxMAAQhAM+iAYio0coIehYEg2bZiiZsRgAUIQDERBMJqAWZRkI4dJiihwkRGDAghBMGiDAMFwIAUAAAD2liDNREQFIBAHQCANMpnbMEgPAAAAAABhIAAADgAAABMEQSwQAAAAAgAAAPQqAcKNAAAAmzYMgUDBa2QQDgQABAAAAOY2DNJzAAvRTBH2B4sjKAAAAAAAYSAAAAsAAAATBEEsEAAAAAEAAAD0GgEAGYQDAQQAAADmNgzScwAL0UwR9geLIygAAAAAAGEgAAALAAAAEwRBLBAAAAABAAAA9CoBABmEAwEEAAAA5jYM0nMAC9FMEfYHiyMoAAAAAABhIAAADQAAABMEQSwQAAAAAQAAAPSqAQAZhAMBBgAAAOY2DNJjb4dwAE1DLAewEM0UYX+wOIICAAAAAABhIAAAEwAAABMEQSwQAAAAAgAAAPQaASiBGgAAww3EAAbTDYMQZBAOBAAAAAgAAADmNgzSY2+HcABNQyw2RwhOMxzAQjRThP3B4giK0QU+AAAAAABhIAAACgAAABMEgQWBfDIIBwIAAAUAAAAHsBDNFGF/sDiCYm5FBSwUAQAAAAAAAABhIAAACgAAABMEAYYDAQAABgAAAObGSADzLEhjfBEBHcBCNFOE/cHiCAoAAAAAAABhIAAAEgAAABMEQSwQAAAABQAAAPQqCsKNAFBsjAAEQRAEQRBEbZAAmzYQwjBsQAQCAWA4EAAAAAQAAADmNgzScwAL0UwR9geLIygAAAAAAGEgAAAaAAAAEwRBLBAAAAAGAAAABBgBoFcRjAAUAuFGAAoekIC+IwAAAAAAi0YggzFcct5hAyI4BuAE1o4YJAAIggE43EGgFAeB4UAHAAAAZpdIAlEZxKPbB7AQzRRhf7A4gmJuwyA9AAAAAAAAAABhIAAAMgAAABMEQSwQAAAAEAAAAPQqgXIoiJIoC8KNAFBsjAAEQRAEQRDeQ5EYIwBBEARBEARB+h/GCEAQBEEQBEEQ/4cxAhAEQRAEQRDk/wEAAACbNjCFMmxABMwAHBOz4YhgIL7pBkIIhiMCRPimGxIh2LRBWp5hAyIQCMAERT6bNlANNGxABAIBmELQZ9MG64mGDYhAIAAzGvls2oBF0rABEQgEgOFAAAAABwAAAOY2DNJjb4wEMM+CNMYXEdABLEQzRdgfLI6gAAAAAAAAYSAAAMkAAAATBEEsEAAAAHAAAACEGwGgVwkQa6hjIAI8eAc8eIehjgMZ8OAd8OAdhjoe6MCDd8CDdxjqOJAJD94BD95hqOMDgwsP3gEP3mGoIxAAPHgHPHiHoY7CEPDgHfDgHYY6EoXAg3fAg3cY6mgcAw/eAQ/eYagjkhA8eAc8eIehjsJI8OAd8OAdhjoKQ8GDd8CDdxjqmKgFD94BD95hqKNxGDx4Bzx4h6GOymrw4B3w4B2GOiLJwYN3wIN3GOpoHAgP3gEP3mGo40AiPHgHPHiHoY5Mk/DgHfDgHYY6No7Cg3fAg3cY6ui8Cg/eAQ/eYagj0yw8eAc8eIehjkzD8OAd8OAdhjoOJMODd8CDdxjqKAwND94BD95hqCMQNjx4Bzx4h6GOMBADDg/eAQ/eYahj4zo8eAc8eIehjkDw8OAd8OAdhjoq68ODd8CDdxjqGAMyAAM8eAc8eIehjkQJAzx4Bzx4h6GOMjADMcCDd8CDdxjqOAM0GAM8eAc8eIehjjRQAzLAg3fAg3cY6jiQMsCDd8CDdxjqKAMzMAM8eAc8eIehjjRQgzPAg3fAg3cY6qgsNMCDd8CDdxjquLAHD94BD95hqGNhCjx4Bzx4BwAAxwbjpYBFFnZwgzZgAwquZMTgAEIQDGwhGNCgDUYMDiAEwcAWguEM2GDE4ABCEAxsIRjMoBgxOIAQBANbCIYyWIMRgwMIQTCwhWAggzEYMTiAEAQDWwgGMQiDEYMDCEEwsIVgAINvxOAAQhAMbCEYPGPE4ABCEAxsIRg6Y8TgAEIQDGwhGLhixOAAQhAMbCEYNjUYMTiAEAQDWwgGLRsxOIAQBANbCAYsDUYMDiAEwcAWguEyRgwOIATBwBaCwTJGDA4gBMHAFoKhKkYMDiAEwcAWgoFSgxGDAwhBMLCFYJikEYMDCEEwsIVgiNJgxOAAQhAMbCEYoGfE4ABCEAxsIRicNhgxOIAQBANbCIaGDUYMDiAEwcAWgoEpRgwOIATBwBaCYVmDEYMDCEEwsIVgUJIRgwMIQTCwhWBADgwHAgAEAAAAB7AQzRRhf7A4gmJuAQMAAAAAAABhIAAAWwEAABMERCwQAAAAKgAAAPQq/58yGAEogaIohFIohiKoAcIVPCBBQQMSFCwgQWEUZCBBAQcSFGggQUEUOCBBAQMSjACUQIECElBsjAAEQRAEQRAEQRAZIwBBEARBEARB/h/GCEAQBEEQBEGQ/5cxAhAEQRAEQRAEQWKMYM3DNmb3/P73fxgjAGF1fNM7FUfaH0YAxghAEARBEAT5/wyJMQIQBEEQBEEQbEFijOBe3Zt3817eW5AAACQGP7Jpgxk4HgUxYgEin+EGNBgDM5hlCIZg0wg1kMIg2jRiDaYwkDaNYAMqDKZNI9qgCgPq3OC8VMQIFTFCRYxQ8RpUvMYsgTBQ8Qa/IZhDMFDxB7shgEEwUPEGRhAbwkDFGyjBTggDFXHgBLMhDFTEgRS8hjBQEQdWsBrC7cF5jw9wWQEawAVnHTYgAjwYACvAQD4WYPC5UMBlBWgAF/x02IAICAIYjiDAQPimG4owCEYMDCAEweKDhX4IhiMCMiC+6YYyEIJLBVxWYAdwwU8piBELCvlYUMFnxMAAQhAsPlgoicCEID4XC7isYA/ggp8OGxABQQBG2IF8LMAD+FgQyOduAZcViAJc8NNhAyIgCMAIMYjPkUHMTAjkY0FFn0IDXdALcLFpBDigwi4EwwZEQBDAhQMuK3gFuOCnFMSIBWBAn+GIgBSEb7qhFIRgOCI4BeKbbkAFIbjgRbcOuKxAF+CCn1IQI5UHRVTADnoBLjaNkAddaIeAghg5JWaWC0x8LBDgYwEhnxIFeoAKnqjAHvQCXGwawQ/kcA8BBTFilRIfCwT5WDAG8bFAgY9RgXwMHYL4DBsQrxAQAJnCa1xJ4LKCeoALzjpsQATEABxK4LKCd4AL1EoBjhxL4LKCfoAL1DpsQAQEAdxL4LKCfIAL1EoBjtxM4LKCkoAL1DpsQAQEAZxN4LKCkIAL1EoBjpxO4LKCloAL1DpsQAQEAZA4vEYFNwHDBgQ5BANwVGzPie0hsV0xoR1Sot7BJmC4IfAJMJhlGIQAw4EAAJkAAAAWHKBIVKMAwxDZthUHKBLVKMAwRPZtxgGKRDUKMAyRjRucgTQPNUl2HKBIVKMAwxDZuUEHKBLVKMAwRPZu0QGKRDUKMAyRzVt2gCJRjQIMQ2T3JimAEBcyCU4z2HOAIlGNAgxDZOsHsBDNFGF/sDiCYtoBikQ1CjAM0U3bdoAiUY0CDEN01zYfoEhUowDDEN220QcoEtUowDBE9231AYpENQowDNGNm32AIlGNAgxDdOd2H6BIVKMAwxDduuEHKBLVKMAwRPdubsMgPaYfoEhUowDDEN287QcoEtUowDBEd2+QAockEJVBPBYaYPhPRNS0jQYYixT5SGWiAcgiRT5S1bXxBygS1SjAMEQ4bf0BikQ1CjAMEV6bf4AiUY0CDEOE2xZ3ONT0UJNkgQKKRDUKMAwRjtt/gCJRjQIMQ4TfNiigSFSjAMMQ4boJCigS1SjAMER4bm+F4FDNdANMRExU1PzB4giKFQooEtUowDBEOH8BkeAMxB8sjqDY/hL5z2GeAYX/RMRunwGF/0QEb6ABhf9ERG+EAopENQowDBG+m6GAIlGNAgxDhPemGoBIVKMAwxDZaoAiUY0CDENU28YaoEhUowDDENW3vQYoEtUowDBENW6wAYpENQowDFGdW2yAIlGNAgxDVOt2G6BIVKMAwxDVu+EGKBLVKMAwRDVvuQGKRDUKMAxR3RuigCJRjQIMQ5TTliigSFSjAMMQ5bUpCigS1SjAMES5bZECyyJFPlL5DXFN1hlA+E9EnMAiOAPxB4sjKLaZBxR+Qxi4/QYoEtUowDBENm3AAYpENQowDJFdAwAAAAAAYSAAAEcAAAATBEEsEAAAABcAAAAEGAGgVwmUQ0GURFkURRGMABQCfUcACFfwgAQjABQbIwBBEARBEARB/B/GCEAQBEEQBEHUBokxAhAEQRAEQRCk/2GMAARBEARBEN5DkRgjAEEQBEEQBEH+HwAAAJs2UEY0bEAE1AAcFbPhiGAgvukGQgiGIwJD+KYbDiHYtEFjrGEDIhAIwARFPps2cM41bEAEAgGYQtBn0wYPwoYNiEAgADMg+WzaAAZSNmxABAIBbNoQBlM2bEAEEgEsGiEGVEbdGJx32IAItAE4gbUjBkkTgmAADrEQjAGmZRgOBAAAAAoAAADmNgzSY2+MBDDPgjTGFxHQASxEM0XYHyyOoBhkwCIJRGUQj277CAAAAAAAAGEgAABHAAAAEwRBLBAAAAAXAAAABBgBoFcJlENBlERZFEURjAAUAn1HAAhX8IAEIwAUGyMAQRAEQRAEQfwfxghAEARBEARB1AaJMQIQBEEQBEEQpP9hjAAEQRAEQRDeQ5EYIwBBEARBEARB/h8AAACbNlBGNGxABNQAHBWz4YhgIL7pBkIIhiMCQ/imGw4h2LRBY6xhAyIQCMAERT6bNnDONWxABAIBmELQZ9MGD8KGDYhAIAAzIPls2gAGUjZsQAQCAWzaEAZTNmxABBIBLBohBlRG3Ricd9iACLQBOIG1IwZJE4JgAA6xEIwBpmUYDgQAAAAKAAAABhnQSAJRGcSj2z7iI+Y2DNJjb4wEMM+CNMYXEdABLEQzRdgfLI6gAAAAAABxIAAAIQEAAFIOECJkgqQcIETI5Eg5QIiQobacEywDsRATwWCD9ChNd4FkENNJMSg1PdQkMdggPbZCFBFB1Ej2no/TbHaY/pa72Gnxi1yGy8vjML1MNiFqWSrGZwhGIib/oRHeR3S8NKh2fZ4eu9hp8YtchsvL4zC9TNYcR4OmAChpehyLiOy/sBSCvmhaa9QLIoOYxOahphWYCAYbpKdEsPd8nGazw/S33MVOi1/jNzwvT5/RdHsowFUzPVMhioiA7GKofboC1kBZZ6frc9DTBZq203Q0CKV+z0FhOmg8lrfDrjk97Da/5WRXmVxP6cs8QQMsiyMAE8Fgg/RUAS9Q0ek5iJ0Wy8PyPCg9B5HLcHl5HKaXyaCwmwxKz0HuNx3UDqfd9HDaXSaDwu58+y0vu0BJOuieZrNB4jJIXm6/7WUyKO0GBevn+pwOksFiN1cdHFPqskVzzaqjadbn6TGImRbLw/K8wvQTIA1hMdggPQUhtcN0tIudFr/Gb3henj6j6UVivefjNJsdpr/lLnZa/GKnx2X3vFwl03s+TrPZYfpb7mKnxS93uF0uEMUcrs/p57K7VdMZ6ILIIKaTYsTmoSaJwQbpKQmoHaajXey0+MVOj8vueVmD9hcSpEEmBhukR3l0DSSkkSagEQhuIYCIwQbp0ZjGgiugkGVwJSISm4mICkAgGGyQHvVRPGgYYgIGYAIYbJCecnjaYTraxU6LX+E6Hf2WlwBlTrPpZbmLnRa/xm94Xp4+o+llghnD9Tkd9JyP02x2mP6Wg5hpsTwsz+uOqcGHNNIENAKxEhIxuRIRic1ERAUgEAw2SE+dWO/5OM1mh+lvuYudFr/sZfk8/XYrSzcBMxDSFDkYgw3SUxtRuz5Pj13stPjFTo/L7nm5JibmEcoE3dN0NKiMH5fh9PTbXQaSOc2ml+Uudlr8YqfHZfe8rD3WBhbSSBPQCATnNNIENJPEYIP02AfRAAxhOEWxOE5UFlA7TEe72Gnxy16Wz9Nvt6EQtV/XapNfIBnEhFLTQ00rMBEMNkhPAUTmNJtelrvYafErXKej3/KKmNphOtrFTotf5DJcXh6H6WVycTjt+jw9drHT4pc73C6XR9Suz9NjFzstftnL8nn67bYbogACqRbQAE2nw+e612s8lrfDrjk97Da/5WRXmVx/+dXv+cucZtPL8vmrEihjuD6ng4xpNr0sBzHTYnlYni+Kph2mo13stPjlDrfLxSCZ02x6We5ip8Uve1k+T7/dFVK95+M0mx2mv+Uudlr8Ctfp6Le8MKB2fZ4eu9hp8Stcp6Pf8lKgzGk2vSx3sdPil7xsLsvL7nHZGojat/siqMxpNr0sd7HT4he5DJeXx2F6maw/1QiM4DAPNREMNkhPZUzt+jw9drHT4tf4Dc/L02c0XYFkFyKkkSagEQixQSYGG6RHdTQNHGEBJElskInBBukxF4MBlsURamBS1tnp+hz0dIGm7TQdDUomkyoDXCAZxMQCzLMQKzARDDZITyE85jSbXpa72Gnxyx1ul6uCaYbpaBAzLZaH5XkAAAAAAAAA",
					"bitcode_size" : 10112,
					"color" : [ 0.50196099281311, 0.50196099281311, 0.50196099281311, 1.0 ],
					"id" : "obj-4",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "signal" ],
					"patching_rect" : [ 781.0, 500.0, 62.0, 22.0 ],
					"serial_number" : "C02W4DCHHTD664 bits",
					"sourcecode" : "import(\"oscillator.lib\");\r\nimport(\"filter.lib\");\r\n\r\nprocess = square(hslider(\"freq\", 100, 10, 8000, 0.01) : smooth(0.999));",
					"sourcecode_size" : 123,
					"text" : "faustgen~",
					"varname" : "faustgen-fe4fb5d0",
					"version" : "1.12"
				}

			}
, 			{
				"box" : 				{
					"bgcolor" : [ 0.094118, 0.113725, 0.137255, 1.0 ],
					"fgcolor" : [ 0.0, 1.0, 0.0, 1.0 ],
					"gridcolor" : [ 0.301961, 0.337255, 0.403922, 0.25098 ],
					"id" : "obj-9",
					"maxclass" : "scope~",
					"numinlets" : 2,
					"numoutlets" : 0,
					"patching_rect" : [ 177.0, 611.0, 100.0, 50.0 ],
					"prototypename" : "M4L.yellow"
				}

			}
, 			{
				"box" : 				{
					"bgcolor" : [ 0.094118, 0.113725, 0.137255, 1.0 ],
					"fgcolor" : [ 0.0, 1.0, 0.0, 1.0 ],
					"gridcolor" : [ 0.301961, 0.337255, 0.403922, 0.25098 ],
					"id" : "obj-8",
					"maxclass" : "scope~",
					"numinlets" : 2,
					"numoutlets" : 0,
					"patching_rect" : [ 283.0, 611.0, 100.0, 50.0 ],
					"prototypename" : "M4L.yellow"
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-5",
					"maxclass" : "newobj",
					"numinlets" : 2,
					"numoutlets" : 1,
					"outlettype" : [ "signal" ],
					"patching_rect" : [ 177.0, 487.0, 53.0, 22.0 ],
					"text" : "cycle~ 6"
				}

			}
, 			{
				"box" : 				{
					"floatoutput" : 1,
					"id" : "obj-2",
					"maxclass" : "slider",
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"parameter_enable" : 0,
					"patching_rect" : [ 283.0, 424.0, 140.0, 20.0 ],
					"size" : 1.0
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-3",
					"maxclass" : "message",
					"numinlets" : 2,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"patching_rect" : [ 283.0, 487.0, 81.0, 22.0 ],
					"text" : "/0x00/gain $1"
				}

			}
, 			{
				"box" : 				{
					"bitcode" : "3sAXCwAAAAAUAAAA+BgAAAcAAAFCQ8DeNRQAAAUAAABiDDAkSVm+5u3zfi1EATIFAAAAACEMAAA0BgAAC4IgAAIAAAATAAAAB4EjkUHIBEkGEDI5kgGEDCUFCBkeBItigBxFAkKSC0LkEDIUOAgYSwoycohIkBQgQ0aIpQAZMkLkSA6QkSPEUEFRgYzhg+WKBDlGBlEYAAAaAAAAG4ggAJYNhPD/////AyBtQIb/////HwA4ACSA2kAQAJBsMAoBWIBqg2EEwAJUG5Dj/////wcADgAJqDYYSAAsALXBSP7///9/AOAAkDYgygAkwAJUG5CFABJgAaoNBvP/////A9AGgARJGAAACgAAABOEQJggBMMEgRAmBMUEwTgmCMgwIRgmCEEyITAmEIGyJBOEgJkQCACJIAAATAAAADIiyAkgZIUEkyOkhASTI+OEoZAUEkyOjAuE5EwQiMMcAZISAAokC4AGWQGgQlIA6JAWAEpkF4AWOQGgRiIA6JEQAIpkCoAmWQCgShoA6JIRAMqkA4A22QCgThIA6JMPAArlAoBGIwAEKELJRKc5AjAYAkgB1T3SFFHC5A/Sw2CD9KAhtVIRqwilFrnmCEChCCYYxUrQolkZSiYT1UhViJLJdCNcQUom002lUqlIV4ySyXRTqYhXipLpZjKR7xppiihh8l0RXCgCNSabzYbK5Xa7Xa/3I2AZSq0gCYuQahGxDKlWioxFKKUIWYZSK0XKQpRMJhMx75GmiBIm3yQmAFwoAgmmJjmLUHoSlG6lKLVSUilN5wiCYpRMAFiqStaBADKRjXaEohQ1pwDmCASCAQATMnzAAzv4BTuggzYIB3iAB3YohzYgh3CQh3tIB3eIAzxwAzhwAzjYUAbl0AbtoAfv0AbpYAd0oAd2QAdtYA54AAd6EAdygAdt4A54oAdxYAd6MAdyoAd2QAdtMAtxIAd4oPNADBkyUkQEYDDkwYDDwAcDFkMfDHgMoTBgMpTCgMtgCgM2wykM+AyqMGA0rMKAxeAHAxbDHww4Da0wYDOgwoDV4AoDRgMrDHgNsjBgM6TCgMcgCgNmwywMeAyjMOA22MKA3YALA2YDLQz4DbkwYDbUwoDHQAoDFgMoDBgMejBgOOjCgNtwCwMGwx4MWA2vMOA47MKA1QALA1ZDLAyGPGcABEAgAAAAAAAAAEMeNwAAQBAAAAAAAACAIY8bAAAQAAAAAAAAAMCQJw6AABgAAAAAAAAAYMjjBgAACAIAAAAAAAAw5JkDAAAGAAAAAAAAABjyiAIAAIQAAAAAAAAADHlIAQCAAgAAAAAAAACGPKQAAIABAAAAAAAAAEMeUgAAwAAAAAAAAACAIY8pAABgAAAAAAAAAMCQxxQAADAAAAAAAAAAYMiDCgAAHAAAAAAAAAAw5HEDAAAQAAAAAAAAABjyuAEAAAgAAAAAAAAADHlUAQAABAAAAAAAAACGPLAAAEACAAAAAAAAAEOeWQAAQAEAAAAAAACAIY8qAACAAAAAAAAAAMCQRxUAAEAAAAAAAAAAYMhjC0AALAAAAAAAAAAg8YFMB4kNAoWRCgAAskAAAACfAAAAMh6YHBkRTJCMCSZHxgRDCmhkTrPpZbmLnRa/wnU6+i3XqF2fp8cudlr8YqfHZfe8rFG7Pk+PXey0+GUvy+fpt5sGugbKOjtdn4OeLtC0naajQSj1ew4K00Hjsbwdds3pYbf5LSe7yuR6igpKmdNselnuYqfFr/Ebnpenz2i6UsZwfU4HGdNselkOYqbF8rA8r5Q5zaaX5S52WvySl81ledk9LivVrs/TYxc7LX6Ry3B5eRyml8l00ElZZ6frc9DTBZq203Q0KJlM6tQO09Eudlr8Ipfh8vI4TC+TdWIeoUzQPU1Hg8r4cRlOT7/dOrXr8/TYxU6LX+M3PC9Pn9F0SmhlTrPpZbmLnRa/yGW4vDwO08tkWigvUNHpOYidFsvD8jwoPQeRy3B5eRyml8mgsJsMSs9B7jcd1A6n3fRw2l0mg8LufPstL7tASTronmazQeIySF5uv+1lMijtBgXr5/qcDpLBYjcXNVQyp9n0stzFTotf7PS47J6XVTKn2fSy3MVOi1/2snyefrtVaofpaBc7LX6N3/C8PH1G0+mhx5S6bNFcM4roY06z6WW5i50Wv9zhdlmfdpiOdrHT4le4Tke/5TRRNEDT6fC57vUaj+XtsGtOD7vNbznZVSbXX371e/4yp9n0snz+osoStW/3SzQAQyxBXzS9hAEgDV22AFfN9CijUDtMR7vYafGLnR6X3fOyQu0wHe1ip8Uve1k+T7/dCrXr8/TYxU6LX+E6Hf2W00abdpiOdrHT4pc73C5r06zP02MQMy2Wh+V56ijTDNPRIGZaLA/L8/TZofZpCqnTrs/TYxc7LX65w+0yjVQxh+tz+rnsbsUAAAAAeRgAAAkAAAAaA0wQMTY2uzYXtrc3OJc6N7k3NjYXsrS5MDG2sg1BsEIYBACxGAAAWgAAADMIgBzE4RxmFAE9iEM4hMOMQoAHeXgHc5hxDOYAD+0QDvSADjMMQh7CwR3OoRxmMAU9iEM4hIMbzAM9yEM9jAM9zHiMdHAHewgHeUiHcHAHenADdniHcCCHGcwRDuyQDuEwD24wD+PwDvBQDjMQxB3eIRzYIR3CYR5mMIk7vIM70EM5tAM8vIM8hAM7zPAUdmAHe2gHN2iHcmgHN4CHcJCHcGAHdigHdvgFdniHd4CHXwiHcRiHcpiHeZiBLO7wDu7gDvXADuwwA2LIoRzkoRzMoRzkoRzcYRzKIRzEgR3KYQbWkEM5yEM5mEM5yEM5uMM4lEM4iAM7lMMvvIM8/II71AM7sMMMx2mHcFiHcnCDdGgHeGCHdBiHdKCHGc5TD+4AD/JQDuSQDuNAD+EgDuxQDjMgKB3cwR7CQR7SIRzcgR7c4Bzk4R3qAR5mGFE4sEM6nIM7zFAkdmAHe2gHN2CHd3gHeAAAAKkYAAAGAAAACwpyKId3gAd6WHCYQz24wziwQznQAwAAYSAAAAgAAAATBAGGAwEAAAQAAAC2NQzScwAL0UwR9geLIygAAAAAAGEgAAAKAAAAEwTBBaYdMSiAEASDM9CDAMOBAAADAAAAB1AQzRRhtjUM0gMAAAAAAGEgAAAIAAAAEwQBhgMBAAAEAAAAtjUM0nMAC9FMEfYHiyMoAAAAAABhIAAADgAAABMEQSwQAAAAAgAAAAQrQAIAAAAAIwYFEIJgEAd2EFzQ2gzCgQAAAAACAAAAB1AQzRRhAAAAAAAAYSAAAC4AAAATBEEsEAAAABMAAAAEGwGgVCGUQUEUAZmGOipLDOCgF+CgF0g1RgCCIAiCIAiC+D+MAIwRgCAIgiAIgiD/D2MEOmvOOWvOOev+A5mGOiorDOCgF+CgFwAAx2SXAhPZwMFpFgpsZMTAAEIQDOogGIoNHKCHoWBHNmuYombEYAFCEAz0QDCagFmUZAOHSYooQJERgwIIQTA4gwDBcCAFAAAAxpUgzUREBSAQB0AgDTLZ1jBIDwAAAAAAYSAAAAkAAAATBMEF3aUgNTIIBwIEAAAAtjUM0nMAC9FMEfYHiyMoAAAAAABhIAAACwAAABMEQSwQAAAAAQAAAJQqAQAZhAMBBAAAALY1DNJzAAvRTBH2B4sjKAAAAAAAYSAAAAsAAAATBEEsEAAAAAEAAACUKgEAGYQDAQQAAAC2NQzScwAL0UwR9geLIygAAAAAAGEgAAATAAAAEwRBLBAAAAACAAAAlBoBKIEaAADDDcQABtMNgxBkEA4EAAAACAAAAAZGCE4z2NYwSI9xHcIBNA2xHMBCNFOE/cHiCIqFBT4AAAAAAGEgAAATAAAAEwRBLBAAAAACAAAAlBoBKIEaAADDDcQABtMNgxBkEA4EAAAACAAAAAZGCE4z2NYwSI9xHcIBNA2xHMBCNFOE/cHiCIqFBT4AAAAAAGEgAAAKAAAAEwQBhgMBAAAGAAAAtsVIAPMsSGN8EQEdwEI0U4T9weIICgAAAAAAAGEgAAASAAAAEwRBLBAAAAAFAAAAlCoCgo0AkGqMAARBEARBEATxfwCbNRDCMGxABAIBYDgQAAAABAAAALY1DNJzAAvRTBH2B4sjKAAAAAAAYSAAABgAAAATBEEsEAAAAAUAAAAEGAGgVAkUBMFGAAqEqiMAAAAAAItFHEMxXGDaEYMECEEwsIU2CBDCGDAcCAgAAAA2hkgCURnEg9vWMEjPASxEM0XYHyyOoJjYIQlEZRAPAAAAAABhIAAADQAAABMEwQndHTYgAmEAMBwIAAAHAAAAtjUM0mNcjAQwz4I0xhcR0AEsRDNF2B8sjqAAAAAAAABhIAAAnwAAABMEQSwQAAAAWAAAAAQbAaBUCZBpqONAJjjgBTjghaGODwwuOOAFOOCFoY5AAOCAF+CAF4Y6BiKAA16AA14Y6igMAQ54AQ54YajjQAY44AU44IWhjkQh4IAX4IAXhjoax4ADXoADXhjqeKADDngBDnhhqCOSEDjgBTjghaGOwkjggBfggBeGOgpDgQNegANeGOqYqAUOeAEOeGGoo3EYOOAFOOCFoY7KauCAF+CAF4Y6IsmBA16AA14Y6mgcCA54AQ54YajjQCI44AU44IWhjkyT4IAX4IAXhjo2joIDXoADXhjq6LwKDngBDnhhqCPTLDjgBTjghaGOTMPggBfggBeGOg4kgwNegANeGOooDA0OeAEOeGGoIxA2OOAFOOCFoY4wEAMODngBDnhhqGPjOjjgBTjghaGOQPDggBfggBeGOirrgwNegANeGOoYAzIAAzjgBTjghaGOhSnggBfggBeGOi7sgQNegANeAABHBtmlwESWczCDMiADCppkxOAAQhAMWCEYxkAMRgwOIATBgBWCIQzAYMTgAEIQDFghGD5jxOAAQhAMWCEYvG7E4ABCEAxYIRi4bcTgAEIQDFghGLRsxOAAQhAMWCEYsGvE4ABCEAxYIRisYsTgAEIQDFghGKpixOAAQhAMWCEYKGPE4ABCEAxYIRimMhgxOIAQBANWCAYpGjE4gBAEA1YIBogMRgwOIATBgBWC4SlGDA4gBMGAFYLBKUYMDiAEwYAVgqExRgwOIATBgBWCgSmDEYMDCEEwYIVgWJQRgwMIQTBghWBIyGDE4ABCEAxYIRiQA8OBAAAAAAQAAAAHsBDNFGF/sDiCYlsBAwAAAAAAAGEgAAAuAQAAEwRJLBAAAAANAAAAlBoBqIEyKIISKASClUEhlEBBjAAUSB1UQQ2QaowAhNXxTe9UHGl/GCNY87CN2T2///0fADTdCE03slnDlUAUqIgFhnyGGzLLDGYZAiTYLGJrpocCFSkOg+owHW4INjCYZSiEoD5NLeBAcAEsTgzAcEEqZgmGgYo7AANhDYaBijsAA+EMhoGKNDCEMRgGKtTgGzDBgko+FkTwuTWAZQUfXHDTYQMiIAiAEhWxoJDPsAGhBARwcADLCsgALggrBTBydADLCswALgjrsAEREARwhGormgNYKmFqg6USKjcYbhjuAAxmGYghMA0OYDBLUAxUqIEoBAwxUAEH4BAQxHCDGOQBGcwyIEZggh2AYKkENgiWSmAD4YoUVDAKMUtwDFSkwS4cgjFQcQe3cCDGQMUdzMLBGAMVavAKh2VYUAfysSAO4HOrAMsK/gAuuOmwAREQBLBUwuEHFKiIGYF8lkpYQmHYgAgEAjhZgGUFpgAXhJUCGDlbgGUFqAAXhHXYgAgIAjhCtRaYgnwsEAX4DBsQT0AASyVUq0CBitgQyGephMwVhg2IQCAAYmBk2IBIAgK4QLUWuIJ8LFAF+AwbEFdAAEsldLJAgYrYEMhnqYQwqIVhAyIQCIAoGBk2IKKAAC5QrQW2IB8LZAE+wwbEFxAAlYGKmBDIZ9iAQIOAAEiDkWED4goI4ALVLpWQBuWwVMIamEO1QTrAcEPwDmAwy4AcAYYDAQCcAAAAxhqASAJRGcRz23IAIglEZRBPbl0G0jzUJBlzACIJRGUQD2+GAYpENQowDJGd22GAIlGNAgxDZPfWGYBIAlEZxKPbbQAiCURlEM9uugGIJBCVQTy2/QYgkkBUBvHgRhmQSAJRGcRj11YZkEgCURnEY98HsBDNFGF/sDiCYogBikQ1CjAM0U3bYoAiUY0CDEN02zcACc5A/MHiCIrtP5GzGGOAIlGNAgxDdOfWGKBIVKMAwxDdum0Ng/QYZIAiUY0CDEN08+YcoBAXMglOM/i3RQYoEtUowDBEd2+PAYpENQowDNG9G2fAIQlEZRCPiQYcixT5SIVbHnJNEYBMRGShAcciRT5S7dYc0CxS5COV3xDXVPdn0AnOQPzB4giK7S+R/xy+9CzI5EvPgkwmGGAsUuQj1QlogjMQf7A4gmL7T+Qs/hMRBwEMRGSnAYpENQowDBFOG2qAIlGNAgxDhNdXcAnOQPzB4giK7S+R/xy+9CzIZF6HQ00PNUnWGqBIVKMAwxDhtmEGED7VRJYZ4CDNUAGR5COVTzWRgQYgixT5SFXzxlUIDtVMh8BExERFzR8sjqBYbIAiUY0CDEOE5xcQCc5A/MHiCIrtL5H/HOYaoEhUowDDEOG3vQYoEtUowDBEOG6yAYpENQowDBGu22yAIlGNAgxDhO+mhywC8/iMM5hpACJRjQIMQ2SBAcgiRT5S2bQBBiCLFPlIZdtHAAaCMxB/sDiCYvtL5D+HLz0LMvmL4zzEhUw2GbAsUuQjld8Q12R3hP9EhKUGJJJAVAbx1PsdLIIzEH+wOIJim2UAQlzIJDjNYMIBiCQQlUE8NQAAATEAAAIAAABbhjaQBAAAAAAAAABhIAAAJAAAABMEQSwQAAAACAAAAAQYAaBUEZRAQVB1BIBgIwAFQqoxAhAEQRAEQRDE/wEAp3R32IAIlAHYrGEhkGEDIhgIYLEIpkCKC0w7YpAwIQgGtiAHAWMkCIYDAQAMAAAAdpZIAlEZxOMjtjUM0mNoiiQQlUE8uI8YFyMBzLMgjfFFBHQAC9FMEfYHiyMoAAAAAAAAAGEgAAAlAAAAEwRBLBAAAAAIAAAABBgBoFQRlEBBUHUEgGAjAAVCqjECEARBEARBEMT/AQCndHfYgAiUAdisYSGQYQMiGAhgsQimQIoLTDtikDAhCAa2IAcBYyQIhgMBAA0AAAC2NQzSY1yMBDDPgjTGFxGQnS2SQFQG8fiIjxzAQjRThP3B4giKoTGSQFQG8eA+4iMAAAAAAAAAAHEgAADzAAAAUg4QImSCpBwgRMjkSDlAiJChlvASLAOxEBPBYIP0KItqgWQQ00kxKDU91CQx2CA9NkIUEUHYDbUsFeMzBCMRk//QCO8jOl4aVLs+T49d7LT4RS7D5eVxmF4mWwhBXzStLbcFkUFMYvNQ0wpMBIMN0mMPBbhqpmcXQ+3TFbAGyjo7XZ+Dni7QtJ2mo0Eo9XsOCtNB47G8HXbN6WG3+S0nu8rkekpPkAkaYFkcAZgIBhukpwp4gYpOz0HstFgeludB6TmIXIbLy+MwvUwGhd1kUHoOcr/poHY47aaH0+4yGRR259tvedkFStJB9zSbDRKXQfJy+20vk0FpNyhYP9fndJAMFru56uCYUpctmmtWHU2zPk+PQcy0WB6W5xVFmgBpCIvBBukpCKkdpqNd7LT4NX7D8/L0GU0vEMUcrs/p57K7FTMRwgCQRlc6CyKDmE6KEZuHmiQGG6SnJKB2mI52sdPiFzs9LrvnZbUJVUiQBpkYbJAejQk0kJBGmoBGILiFACIGG6RHU8QJroBClsGViEhsJiIqAIFgsEF6dEbVoGGICRiACWCwQXrK4WmH6WgXOy1+het09FteApQ5zaaX5S52Wvwav+F5efqMpitMe8GHNNIENAKxEhIxuRIRic1ERAUgEAw2SI+SyBIwAyFNkYMx2CA9tRG16/P02MVOi1/s9LjsnpdrYmIeoUzQPU1Hg8r4cRlOT7/dZSCZ02x6We5ip8Uvdnpcds/LKrNpYCGNNAGNQHBOI01AM0kMNkiPfRANwBBlAbXDdLSLnRa/7GX5PP12qwtzgWQQE0pNDzWtwEQw2CA9BRCZ02x6We5ip8WvcJ2OfssrYmqH6WgXOy1+kctweXkcppfJxeG06/P02MVOi1/ucLtcHlG7Pk+PXey0+GUvy+fpt7sW0ABNp8PnutdrPJa3w645Pew2v+VkV5lcf/nV7/nLnGbTy/L5qxIoY7g+p4OMaTa9LAcx02J5WJ4viqYdpqNd7LT45Q63y8UgmdNselnuYqfFL3tZPk+/3YUBtevz9NjFTotf4Tod/ZaXAmVOs+lluYudFr/kZXNZXnaPy9ZA1L7dF0FlTrPpZbmLnRa/yGW4vDwO08tkpVk+YASHeaiJYLBBeipjatfn6bGLnRa/xm94Xp4+o+las58QIY00AY1AiA0yMdggPfoSXuAICyBJYoNMDDZIj5kYDLAsjlADk7LOTtfnoKcLNG2n6WhQMplUFckCySAmFmCehViBiWCwQXoK4TGn2fSy3MVOi1/ucLtcFUwzTEeDmGmxPCzPAwAAAAAAAAAAAAA=",
					"bitcode_size" : 8556,
					"color" : [ 0.50196099281311, 0.50196099281311, 0.50196099281311, 1.0 ],
					"id" : "obj-1",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "signal" ],
					"patching_rect" : [ 283.0, 552.0, 180.0, 22.0 ],
					"serial_number" : "C02W4DCHHTD664 bits",
					"sourcecode" : "import(\"filter.lib\");\r\n\r\ngainController = *(gain : smooth(0.999))\r\nwith {\r\n\tgain = hslider(\"gain\", 0.5, 0, 1, 0.1);\r\n};\r\n\r\nprocess = gainController;",
					"sourcecode_size" : 148,
					"text" : "faustgen~ simple-gain-controller",
					"varname" : "faustgen-fe596e10",
					"version" : "1.12"
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-7",
					"maxclass" : "ezdac~",
					"numinlets" : 2,
					"numoutlets" : 0,
					"patching_rect" : [ 656.0, 914.0, 45.0, 45.0 ]
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-6",
					"maxclass" : "gain~",
					"multichannelvariant" : 0,
					"numinlets" : 1,
					"numoutlets" : 2,
					"outlettype" : [ "signal", "" ],
					"parameter_enable" : 0,
					"patching_rect" : [ 656.0, 741.0, 22.0, 140.0 ]
				}

			}
 ],
		"lines" : [ 			{
				"patchline" : 				{
					"destination" : [ "obj-8", 0 ],
					"source" : [ "obj-1", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-11", 0 ],
					"order" : 0,
					"source" : [ "obj-10", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-4", 0 ],
					"order" : 1,
					"source" : [ "obj-10", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-3", 0 ],
					"source" : [ "obj-2", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-1", 0 ],
					"source" : [ "obj-3", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-13", 0 ],
					"order" : 0,
					"source" : [ "obj-4", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-6", 0 ],
					"order" : 1,
					"source" : [ "obj-4", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-1", 0 ],
					"order" : 0,
					"source" : [ "obj-5", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-9", 0 ],
					"order" : 1,
					"source" : [ "obj-5", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-7", 1 ],
					"order" : 0,
					"source" : [ "obj-6", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-7", 0 ],
					"order" : 1,
					"source" : [ "obj-6", 0 ]
				}

			}
 ],
		"dependency_cache" : [ 			{
				"name" : "faustgen~.mxo",
				"type" : "iLaX"
			}
 ],
		"autosave" : 0
	}

}
